name: Sync to Private Repo

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Debug Info
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Git status:"
          git status
          echo "Git remote:"
          git remote -v

      - name: Push to Private Repository
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
        run: |
          echo "Removing existing private remote if it exists..."
          git remote remove private || true
          
          echo "Setting up private remote..."
          git remote add private "https://${TARGET_TOKEN}@github.com/vincitamore/private-showcase.git"
          
          echo "Fetching from private remote..."
          git fetch private || echo "Failed to fetch from private remote"
          
          echo "Pushing to private repository..."
          git push private main:main --force
          
          echo "Verifying push..."
          git ls-remote private 