name: Sync to Private Repo

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.TARGET_REPO_TOKEN }}"
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Push to Private Repository
        env:
          REPO: ${{ secrets.PRIVATE_REPO_URL }}
        run: |
          echo "Setting up private remote..."
          REPO_URL="https://github.com/${REPO#github.com/}"
          echo "Using repository: ${REPO_URL}"
          
          git remote add private "${REPO_URL}"
          echo "Remote added, attempting push..."
          git push private main:main --force 