name: Sync to Private Repo

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Push to Private Repository
        env:
          TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
          REPO: ${{ secrets.PRIVATE_REPO_URL }}
        run: |
          echo "Setting up private remote..."
          # Debug output (safe)
          echo "REPO value length: ${#REPO}"
          echo "First part of REPO: $(echo $REPO | cut -d'/' -f1)"
          
          # Remove any trailing slashes from REPO
          CLEAN_REPO=$(echo "${REPO}" | sed 's#/$##')
          echo "Clean REPO value length: ${#CLEAN_REPO}"
          
          # Construct URL (without exposing token)
          REPO_URL="https://${TOKEN}@${CLEAN_REPO}"
          echo "Final URL length: ${#REPO_URL}"
          
          # Add remote and push
          git remote add private "${REPO_URL}"
          echo "Remote added, attempting push..."
          git push private main:main --force 