name: Sync to Private Repo

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Push to Private Repository
        env:
          TARGET_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
          PRIVATE_REPO_URL: ${{ secrets.PRIVATE_REPO_URL }}
        run: |
          echo "Setting up private remote..."
          git remote add private "https://${TARGET_TOKEN}@${PRIVATE_REPO_URL}"
          
          echo "Pushing to private repository..."
          git push private main:main --force 